name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run script
      run: |
        python main.py
    - name: Save result to a file
      run: |
        cat result.txt
        echo "::set-output name=result::$(cat result.txt)"
    - name: Use result in another step
      run: |
        echo "The result of the addition is: ${{ steps.run-script.outputs.result }}"
 
