name: Python application

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run script
      id: run-script
      run: |
        python main.py
    - name: Save result to a file
      id: save-result
      run: |
        cat result.txt
        echo "result=$(cat result.txt)" >> $GITHUB_ENV
    - name: Use result in another step
      run: |
        echo "The result of the addition is: ${{ env.result }}" 
